### ISSUE TITLE
Javascript file to get the Weather API data

### ISSUE THREAD

**Issue by AlexTheAmateur** [jojobautistaum/weather-riders#11]
The information we would like to pull and present from the weather API include:
- The temperature at the location (city) and time
- The Windchill
- Type of weather (sunny/rainy/snowy/etc)

**Comment by jojobautistaum** [comment]
Here is the console log from JS files of the weather info we might be interested in:

![image](https://user-images.githubusercontent.com/90885263/142241757-f1cdd1d7-d0d0-403b-9842-4458cf7fed16.png)
